function showErr(m){var b=document.getElementById('errBanner');b.style.display='block';b.textContent='⚠️ Erro: '+m;}
var K={jardim:'vesper_jardim',notas:'vesper_notas',ativ:'vesper_atividade',temas:'vesper_temas',pref:'vesper_pref',vis:'vesper_visitas'};
var MEM={},LS_OK=(function(){try{localStorage.setItem('__t','1');localStorage.removeItem('__t');return true}catch(e){return false}})();
function jget(k,d){try{var v=LS_OK?localStorage.getItem(k):(MEM[k]||null);return v?JSON.parse(v):d}catch(e){return d}}
function jset(k,v){try{var s=JSON.stringify(v);if(LS_OK)localStorage.setItem(k,s);else MEM[k]=s}catch(e){}}
function fmt(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function today(){return fmt(new Date())}
function salt(){var s=jget('vesper_salt',null);if(!s){s='s'+Math.random().toString(36).slice(2);jset('vesper_salt',s)}return s}
function hash(t){var h=5381;for(var i=0;i<t.length;i++){h=((h<<5)+h+t.charCodeAt(i))|0}return 'h'+(h>>>0).toString(36)}
var QS=['Nome do seu primeiro animal de estimação?','Cidade onde você nasceu?','Qual seu doce favorito?','Nome da sua primeira professora?'];
var WORDS=['sol','jardim','chuva','estrela','mel','rosa','vento','lua','flor','mar','nuvem','campo','luz','terra','rio','brisa','ouro','vida','sonho','paz','alma','céu','verde','doce'];
var S=null,entered=false,curPhrase='',recMode='ph',recOk=false,attempts=0;
function showAuth(m){document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('on')});document.getElementById('s-auth').classList.add('on');document.getElementById('backBtn').style.display='none';document.getElementById('lockBtn').style.display='none';document.getElementById('wallet').style.display='none';document.getElementById('bottomNav').classList.remove('show');
['authOnboard','authLogin','authRecover','authNewPass'].forEach(function(id){document.getElementById(id).style.display='none'});
document.getElementById(m==='onboard'?'authOnboard':m==='login'?'authLogin':m==='recover'?'authRecover':'authNewPass').style.display='block';
if(m==='recover'){setRc(recMode);document.getElementById('rcQText').textContent='❓ '+QS[S?S.q:0];}}
function genPhrase(){var p=[];while(p.length<6){var w=WORDS[Math.floor(Math.random()*WORDS.length)];if(p.indexOf(w)<0)p.push(w)}return p.join(' ')}
function obFail(m,btn){toast(m);if(btn){btn.disabled=false;btn.textContent='🌻 Plantar meu jardim'}return}
function createJardim(){var btn=document.getElementById('obBtn');btn.disabled=true;btn.textContent='🌱 Plantando...';
var nome=document.getElementById('obNome').value.trim();var p1=document.getElementById('obPass').value;var p2=document.getElementById('obPass2').value;var q=parseInt(document.getElementById('obQ').value);var a=document.getElementById('obA').value.trim();
if(!nome)return obFail('Digite seu nome 🌱',btn);
if(p1&&p1.length<4)return obFail('Senha: mínimo 4 caracteres',btn);
if(p1&&p1!==p2)return obFail('As senhas não conferem',btn);
if(p1&&!a)return obFail('Responda a pergunta secreta 🔑',btn);
curPhrase=genPhrase();
S={nome:nome,passHash:p1?hash(p1+salt()):null,q:q,qHash:hash(a.toLowerCase()+salt()),phraseHash:hash(curPhrase.toLowerCase().trim()),criadoEm:new Date().toISOString(),coins:0,hearts:0,unlocked:[1],saved:[],read:[],savedWords:[],lastBonus:'',lastSave:''};
jset(K.jardim,S);log('conta','Jardim criado por '+nome,'🌱');
if(p1){document.getElementById('phraseWords').textContent=curPhrase;document.getElementById('phraseModal').classList.add('on');}else{enter();}}
function copyPhrase(){navigator.clipboard.writeText(curPhrase).then(function(){toast('Frase copiada! Guarde bem 📋')}).catch(function(){toast('Copie manualmente: '+curPhrase)})}
function closePhrase(){document.getElementById('phraseModal').classList.remove('on');enter();}
function tryLogin(){if(!S)return;var p=document.getElementById('lgPass').value;
if(!S.passHash){enter();return}
if(hash(p+salt())===S.passHash){attempts=0;enter();}else{attempts++;toast(attempts>=5?'Use "Esqueci minha senha" 🔑':'Senha incorreta ('+attempts+'/5)');}}
function setRc(m){recMode=m;document.getElementById('rcT-ph').classList.toggle('on',m==='ph');document.getElementById('rcT-q').classList.toggle('on',m==='q');document.getElementById('rcPh').style.display=m==='ph'?'block':'none';document.getElementById('rcQ').style.display=m==='q'?'block':'none';}
function tryRecover(){if(!S)return;var ok=false;
if(recMode==='ph'){ok=hash(document.getElementById('rcPhrase').value.toLowerCase().trim())===S.phraseHash;}
else{ok=hash(document.getElementById('rcAns').value.trim().toLowerCase()+salt())===S.qHash;}
if(ok){recOk=true;showAuth('newpass');toast('Identidade confirmada! ✅');}else toast('Não confere. Tente de novo 🔑');}
function setNewPass(){if(!recOk)return;var p1=document.getElementById('npPass').value,p2=document.getElementById('npPass2').value;
if(p1.length<4){toast('Mínimo 4 caracteres');return}if(p1!==p2){toast('Não conferem');return}
S.passHash=hash(p1+salt());recOk=false;curPhrase=genPhrase();S.phraseHash=hash(curPhrase.toLowerCase().trim());jset(K.jardim,S);
document.getElementById('phraseWords').textContent=curPhrase;document.getElementById('phraseModal').classList.add('on');
log('conta','Senha redefinida','🔑');}
function lockApp(){entered=false;stopAllGames();document.getElementById('lgPass').value='';showAuth('login');toast('Jardim trancado 🔒');}
function wipeAll(){if(!confirm('Apagar TUDO deste aparelho (jardim, notas, registro)?'))return;Object.keys(K).forEach(function(k){try{localStorage.removeItem(k)}catch(e){}});location.reload();}
function save(){jset(K.jardim,S);hud();}
function hud(){if(!S)return;document.getElementById('coinView').textContent=S.coins;document.getElementById('heartView').textContent=S.hearts;}
function NM(){return S?S.nome:'você'}
function log(tipo,detalhe,valor){var a=jget(K.ativ,[]);a.unshift({ts:new Date().toISOString(),tipo:tipo,pessoa:NM(),detalhe:detalhe,valor:valor||''});if(a.length>500)a.length=500;jset(K.ativ,a);}
function addCoins(n){if(!n||n<=0)return;S.coins+=n;save();toast('+'+n+' moedas 🪙');log('moedas','Ganhou moedas','+'+n+' 🪙');}
function buzz(ms){try{navigator.vibrate&&navigator.vibrate(ms||10)}catch(e){}}
function cur(){var s=document.querySelector('.screen.on');return s?s.id.replace('s-',''):'auth'}
var hist=[];
function go(id){if(!entered){showAuth('login');return}stopAllGames();hist.push(cur());document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('on')});document.getElementById('s-'+id).classList.add('on');document.getElementById('backBtn').style.display='flex';document.querySelectorAll('#bottomNav button').forEach(function(b){b.classList.toggle('on',b.id==='nv-'+id)});if(id==='tempo')renderTempo();if(id==='diary')renderDiary();if(id==='registro')renderRegistro();window.scrollTo(0,0);}
function goBack(){stopAllGames();var p=hist.pop()||'message';document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('on')});document.getElementById('s-'+p).classList.add('on');document.querySelectorAll('#bottomNav button').forEach(function(b){b.classList.toggle('on',b.id==='nv-'+p)});}
function toast(m){var t=document.getElementById('toast');t.textContent=m;t.style.display='block';setTimeout(function(){t.style.display='none'},2600);}
function confetti(){var cs=getComputedStyle(document.documentElement);var cols=[cs.getPropertyValue('--accent').trim(),cs.getPropertyValue('--accent2').trim(),'#fbbf24','#ffffff'];for(var i=0;i<30;i++){(function(i){setTimeout(function(){var e=document.createElement('div');e.className='confetti';e.style.left=Math.random()*100+'vw';e.style.background=cols[i%4];document.body.appendChild(e);setTimeout(function(){e.remove()},3200)},i*40)})(i)}}
function enter(){entered=true;var v=jget(K.vis,[]);if(v.indexOf(today())<0){v.push(today());jset(K.vis,v)}log('visita','Entrou no jardim','🌻');refreshTheme();hud();document.getElementById('wallet').style.display='flex';document.getElementById('lockBtn').style.display='flex';document.getElementById('gardenName').textContent='Jardim de '+NM();document.getElementById('bottomNav').classList.add('show');go2('message');renderMessage();confetti();toast('Bem-vinda ao seu jardim, '+NM()+'! 🌻');}
function go2(id){document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('on')});document.getElementById('s-'+id).classList.add('on');document.querySelectorAll('#bottomNav button').forEach(function(b){b.classList.toggle('on',b.id==='nv-'+id)});window.scrollTo(0,0);}
var THEMES=[
{id:'primavera',nome:'Primavera em Flor',emoji:'🌸',bg1:'#f9a8d4',bg2:'#86efac',ac:'#ec4899',ac2:'#10b981',card:'#fdf2f8',frase:'🌸 Primavera: tempo de florescer!'},
{id:'verao',nome:'Verão Solar',emoji:'☀️',bg1:'#fb923c',bg2:'#f43f5e',ac:'#f97316',ac2:'#fbbf24',card:'#fff7ed',frase:'☀️ Verão: energia de sol pra você!'},
{id:'outono',nome:'Outono Aconchego',emoji:'🍁',bg1:'#d97706',bg2:'#7c2d12',ac:'#b45309',ac2:'#fbbf24',card:'#fef3c7',frase:'🍁 Outono: aconchego e calma.'},
{id:'inverno',nome:'Inverno Cobertor',emoji:'☕',bg1:'#475569',bg2:'#1e293b',ac:'#6366f1',ac2:'#a5b4fc',card:'#f1f5f9',frase:'☕ Inverno: descansar também é florescer.'},
{id:'flores',nome:'Flores Amarelas',emoji:'🌻',bg1:'#667eea',bg2:'#5b3d8f',ac:'#e8930c',ac2:'#f5c33b',card:'#f2f4fb',frase:'🌻 Memória viva: 21 de setembro!'},
{id:'natal',nome:'Natal de Luz',emoji:'🎄',bg1:'#166534',bg2:'#14532d',ac:'#dc2626',ac2:'#f87171',card:'#fef2f2',frase:'🎄 Natal: luz e gratidão.'},
{id:'anonovo',nome:'Ano Novo',emoji:'🎆',bg1:'#1e3a8a',bg2:'#0f172a',ac:'#fbbf24',ac2:'#fde68a',card:'#eff6ff',frase:'🎆 Ano Novo: novo ciclo floresce.'}];
var EVENTS=[{t:'flores',i:[9,21],f:[9,23]},{t:'natal',i:[12,15],f:[12,26]},{t:'anonovo',i:[12,30],f:[1,3]}];
function season(m){return (m>=3&&m<=5)?'outono':(m>=6&&m<=8)?'inverno':(m>=9&&m<=11)?'primavera':'verao'}
function inEv(e,m,d){var st=e.i[0]*100+e.i[1],en=e.f[0]*100+e.f[1],cu=m*100+d;return st<=en?(cu>=st&&cu<=en):(cu>=st||cu<=en)}
function themeFor(y,m,d){for(var i=0;i<EVENTS.length;i++){if(inEv(EVENTS[i],m,d))return EVENTS[i].t}return season(m)}
var curTheme=null,manualTheme=jget(K.pref,{}).manual||null;
function applyTheme(id){var t=THEMES.filter(function(x){return x.id===id})[0]||THEMES[0];var r=document.documentElement.style;r.setProperty('--bg1',t.bg1);r.setProperty('--bg2',t.bg2);r.setProperty('--accent',t.ac);r.setProperty('--accent2',t.ac2);r.setProperty('--card',t.card);document.getElementById('themeEmoji').textContent=t.emoji;document.getElementById('themeFrase').textContent=t.frase;curTheme=id;var l=jget(K.temas,[]);if(l.indexOf(id)<0){l.push(id);jset(K.temas,l)}}
function refreshTheme(){var d=new Date();applyTheme(manualTheme||themeFor(d.getFullYear(),d.getMonth()+1,d.getDate()))}
function setManual(id){manualTheme=id;var p=jget(K.pref,{});p.manual=id;jset(K.pref,p);refreshTheme();if(entered)renderTempo();toast(id?'Modo memória ativado 📸':'Tema automático 🌻');}
var MSGS=[["{n}, você é aquela pessoa rara que transforma a vida dos outros apenas com sua presença.","Continue sendo essa força da natureza! 💛✨"],["Sua amizade é como um girassol: sempre busca a luz e ilumina todos ao redor.","Você é presente pra quem te conhece! 🌻"],["{n}, sua força e determinação são verdadeiramente inspiradoras.","Continue acreditando no seu potencial! ✨"],["Cada risada sua é contagiante e transforma dias comuns.","Seu sorriso é medicina! 😊💛"],["Você tem um coração enorme e uma alma que brilha mais que o sol.","O mundo precisa de mais pessoas como você! 💫"],["{n}, sua energia positiva transforma qualquer ambiente.","Continue sendo inspiração! 🌟"],["Sua amizade é um tesouro raro guardado com carinho.","Pessoas como você fazem a vida valer a pena! 💛"],["Você é prova viva de que bondade e alegria mudam o mundo.","Continue espalhando amor! 🌻"],["{n}, sua resiliência é admirável: graça de guerreira.","Cada desafio te fortalece! 💪"],["Sua criatividade e inteligência são impressionantes.","Continue explorando seus talentos! 🚀"],["Você tem o dom de fazer todos se sentirem acolhidos.","Seu coração é presente! 💛"],["{n}, sua autenticidade é sua maior força.","Nunca apague seu brilho! ✨"],["Sua alegria transforma qualquer dia em celebração.","Continue espalhando felicidade! 🎉"],["Você é aquela amiga leal, carinhosa e incrível.","Sua amizade é tesouro! 💛"],["{n}, sua determinação é inspiradora. Imparável.","Persiga seus sonhos! 🌟"],["Sua presença traz paz: porto seguro.","Raio de sol em dia nublado! ☀️"],["{n}, você é mais forte e mais amada do que pensa.","Acredite em você! 💪"],["Sua bondade faz do mundo um lugar melhor.","Continue espalhando amor! 💛"],["Você tem luz que ilumina dias escuros.","Sua energia é mágica! ✨"],["{n}, você é rara e verdadeiramente especial.","O mundo é melhor com você! 🌻💛"]];
function dayOfYear(){var n=new Date();return Math.floor((n-new Date(n.getFullYear(),0,0))/864e5)}
function renderMessage(){document.getElementById('msgTitle').textContent='Sua Mensagem de Hoje, '+NM()+' ✨';var m=MSGS[Math.floor((dayOfYear()-1)/18.25)%20];document.getElementById('msgQuote').textContent='"'+m[0].split('{n}').join(NM())+'"';document.getElementById('msgReflect').textContent=m[1];document.getElementById('msgEd').textContent='Edição #'+dayOfYear();var pill=document.getElementById('bonusPill');if(S.lastBonus!==today()){S.hearts+=3;S.lastBonus=today();save();pill.textContent='💛 Bônus Diário: +3 Corações! ✨';log('bonus','Bônus diário coletado','+3 💛');}else pill.textContent='💛 Bônus de hoje já coletado.';}
function saveHeart(){if(S.lastSave===today()){toast('Você já salvou hoje! 💛');return}S.lastSave=today();S.hearts+=1;save();toast('Salvo no coração! +1 💛');log('coracao','Salvou a mensagem','+1 💛');confetti();}
var calView=new Date();
setInterval(function(){var n=new Date();var c=document.getElementById('clock');if(c)c.textContent=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0')+':'+String(n.getSeconds()).padStart(2,'0')},1000);
function calMove(d){calView.setMonth(calView.getMonth()+d);renderCal()}
function renderCal(){var y=calView.getFullYear(),m=calView.getMonth();document.getElementById('calTitle').textContent=calView.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});var notas=jget(K.notas,[]),vis=jget(K.vis,[]);var h='';['D','S','T','Q','Q','S','S'].forEach(function(d){h+='<div class="calDow">'+d+'</div>'});for(var i=0;i<new Date(y,m,1).getDay();i++)h+='<div class="calDay blank"></div>';for(var d=1;d<=new Date(y,m+1,0).getDate();d++){var ds=fmt(new Date(y,m,d));var ev=null;for(var e=0;e<EVENTS.length;e++){if(inEv(EVENTS[e],m+1,d)){ev=EVENTS[e];break}}var nn=notas.filter(function(n){return n.data===ds});var mk='';if(ev)mk+=THEMES.filter(function(t){return t.id===ev.t})[0].emoji;if(nn.some(function(n){return n.arcada}))mk+='◦';else if(nn.length)mk+='•';if(vis.indexOf(ds)>=0)mk+='✓';h+='<div class="calDay'+(ds===today()?' today':'')+'" onclick="showDay(\''+ds+'\')">'+d+'<span class="mk">'+mk+'</span></div>'}document.getElementById('calGrid').innerHTML=h;}
function showDay(ds){var notas=jget(K.notas,[]).filter(function(n){return n.data===ds});document.getElementById('dayPanel').innerHTML='<div class="quote-card"><b style="color:#8a3c1a">📅 '+new Date(ds+'T12:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'long'})+'</b>'+(notas.length?notas.map(function(n){return '<p class="sub" style="margin:6px 0">'+(n.humor||'📝')+' '+(n.titulo||n.texto.slice(0,40)+'...')+'</p>'}).join(''):'<p class="sub" style="margin:6px 0">Nenhuma anotação neste dia.</p>')+'<button class="btn mini gold" onclick="newNote(\''+ds+'\')">✍️ Anotar neste dia</button></div>';}
function renderTempo(){var n=new Date();document.getElementById('dateFull').textContent=n.toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long',year:'numeric'});var h=n.getHours();document.getElementById('greet').textContent=(h<12?'☀️ Bom dia':h<18?'🌤️ Boa tarde':'🌙 Boa noite')+', '+NM()+'! O Vesper acompanha você.';var act=null;for(var i=0;i<EVENTS.length;i++){if(inEv(EVENTS[i],n.getMonth()+1,n.getDate())){act=EVENTS[i];break}}var cd='';if(act){var t=THEMES.filter(function(x){return x.id===act.t})[0];cd='🎉 Modo ativo hoje: '+t.emoji+' '+t.nome+'!';}else{var ne=null;for(var y=n.getFullYear();y<=n.getFullYear()+1&&!ne;y++){for(var e=0;e<EVENTS.length;e++){var st=new Date(y,EVENTS[e].i[0]-1,EVENTS[e].i[1]);if(st>=new Date(n.getFullYear(),n.getMonth(),n.getDate())){ne={t:THEMES.filter(function(x){return x.id===EVENTS[e].t})[0],days:Math.ceil((st-n)/864e5)};break}}}}cd=ne?'⏳ Faltam '+ne.days+' dias para '+ne.t.emoji+' '+ne.t.nome:'';}document.getElementById('countdown').textContent=cd;renderCal();document.getElementById('memGallery').innerHTML=jget(K.temas,[]).map(function(id){var t=THEMES.filter(function(x){return x.id===id})[0];return t?'<button class="btn mini ghost" onclick="setManual(\''+id+'\')">'+t.emoji+' '+t.nome+'</button>':''}).join(' ');document.getElementById('autoThemeBtn').style.display=manualTheme?'flex':'none';}
var diaryTab='all',editingId=null,saveTimer=null,curMood='😊';
var MOODS=['😊','😌','😔','💪','🙏',''];
function setDiaryTab(t){diaryTab=t;['all','pin','arc'].forEach(function(x){document.getElementById('dt-'+x).classList.toggle('on',x===t)});renderDiary();}
function renderDiary(){var q=(document.getElementById('searchNote').value||'').toLowerCase();var notas=jget(K.notas,[]);if(diaryTab==='pin')notas=notas.filter(function(n){return n.fixada&&!n.arcada});else if(diaryTab==='arc')notas=notas.filter(function(n){return n.arcada});else notas=notas.filter(function(n){return !n.arcada});if(q)notas=notas.filter(function(n){return ((n.titulo||'')+n.texto).toLowerCase().indexOf(q)>=0});notas.sort(function(a,b){return (b.data||'').localeCompare(a.data||'')});document.getElementById('noteList').innerHTML=notas.length?notas.map(function(n){return '<div class="note-item'+(n.fixada?' pin':'')+(n.arcada?' arc':'')+'"><b>'+(n.humor||'📝')+' '+(n.titulo||'Sem título')+'</b><p>'+n.texto.slice(0,120)+(n.texto.length>120?'...':'')+'</p><div class="note-meta">📅 '+n.data+(n.fixada?' • 📌':'')+(n.arcada?' • 🗄️':'')+'</div><button class="btn mini ghost" onclick="editNote(\''+n.id+'\')">✏️ Abrir</button></div>'}).join(''):'<p class="sub">Nenhuma anotação por aqui ainda. 🌸</p>';}
function newNote(data){editingId=null;go('note');document.getElementById('nData').value=data||today();document.getElementById('nTitulo').value='';document.getElementById('nTexto').value='';curMood='😊';renderMoods();document.getElementById('saveState').textContent='';updNoteBtns(null);}
function editNote(id){var n=jget(K.notas,[]).filter(function(x){return x.id===id})[0];if(!n)return;editingId=id;go('note');document.getElementById('nData').value=n.data;document.getElementById('nTitulo').value=n.titulo||'';document.getElementById('nTexto').value=n.texto;curMood=n.humor||'😊';renderMoods();updNoteBtns(n);}
function renderMoods(){document.getElementById('moodPick').innerHTML=MOODS.map(function(m){return '<button class="chip'+(m===curMood?' on':'')+'" onclick="pickMood(\''+m+'\')">'+m+'</button>'}).join('');}
function pickMood(m){curMood=m;renderMoods();autoSave();}
function updNoteBtns(n){document.getElementById('pinBtn').textContent=n&&n.fixada?'📌 Desafixar':'📌 Fixar';document.getElementById('arcBtn').textContent=n&&n.arcada?'🗄️ Restaurar':'🗄️ Arcar';}
function autoSave(){clearTimeout(saveTimer);document.getElementById('saveState').textContent='✍️ escrevendo...';saveTimer=setTimeout(function(){if(persistNote())document.getElementById('saveState').textContent='💾 salvo automaticamente';},600);}
function persistNote(){var titulo=document.getElementById('nTitulo').value,texto=document.getElementById('nTexto').value;if(!editingId&&!titulo.trim()&&!texto.trim())return null;var notas=jget(K.notas,[]);var data={id:editingId||('n_'+Date.now()),data:document.getElementById('nData').value||today(),titulo:titulo,texto:texto,humor:curMood,fixada:false,arcada:fa
