function showErr(m){var b=document.getElementById('errBanner');b.style.display='block';b.textContent='⚠️ Erro: '+m;}
var K={jardim:'vesper_jardim',notas:'vesper_notas',ativ:'vesper_atividade',temas:'vesper_temas',pref:'vesper_pref',vis:'vesper_visitas'};
var MEM={},LS_OK=(function(){try{localStorage.setItem('__t','1');localStorage.removeItem('__t');return true}catch(e){return false}})();
function jget(k,d){try{var v=LS_OK?localStorage.getItem(k):(MEM[k]||null);return v?JSON.parse(v):d}catch(e){return d}}
function jset(k,v){try{var s=JSON.stringify(v);if(LS_OK)localStorage.setItem(k,s);else MEM[k]=s}catch(e){}}
function fmt(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function today(){return fmt(new Date())}
function salt(){var s=jget('vesper_salt',null);if(!s){s='s'+Math.random().toString(36).slice(2);jset('vesper_salt',s)}return s}
function hash(t){var h=5381;for(var i=0;i<t.length;i++){h=((h<<5)+h+t.charCodeAt(i))|0}return 'h'+(h>>>0).toString(36)}
var QS=['Nome do seu primeiro animal de estimação?','Cidade onde você nasceu?','Qual seu doce favorito?','Nome da sua primeira professora?'];
var WORDS=['sol','jardim','chuva','estrela','mel','rosa','vento','lua','flor','mar','nuvem','campo','luz','terra','rio','brisa','ouro','vida','sonho','paz','alma','céu','verde','doce'];
var S=null,entered=false,curPhrase='',recMode='ph',recOk=false,attempts=0;
function showAuth(m){document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('on')});document.getElementById('s-auth').classList.add('on');document.getElementById('backBtn').style.display='none';document.getElementById('lockBtn').style.display='none';document.getElementById('wallet').style.display='none';document.getElementById('bottomNav').classList.remove('show');
['authOnboard','authLogin','authRecover','authNewPass'].forEach(function(id){document.getElementById(id).style.display='none'});
document.getElementById(m==='onboard'?'authOnboard':m==='login'?'authLogin':m==='recover'?'authRecover':'authNewPass').style.display='block';
if(m==='recover'){setRc(recMode);document.getElementById('rcQText').textContent='❓ '+QS[S?S.q:0];}}
function genPhrase(){var p=[];while(p.length<6){var w=WORDS[Math.floor(Math.random()*WORDS.length)];if(p.indexOf(w)<0)p.push(w)}return p.join(' ')}
function obFail(m,btn){toast(m);if(btn){btn.disabled=false;btn.textContent='🌻 Plantar meu jardim'}return}
function createJardim(){var btn=document.getElementById('obBtn');btn.disabled=true;btn.textContent='🌱 Plantando...';
var nome=document.getElementById('obNome').value.trim();var p1=document.getElementById('obPass').value;var p2=document.getElementById('obPass2').value;var q=parseInt(document.getElementById('obQ').value);var a=document.getElementById('obA').value.trim();
if(!nome)return obFail('Digite seu nome 🌱',btn);
if(p1&&p1.length<4)return obFail('Senha: mínimo 4 caracteres',btn);
if(p1&&p1!==p2)return obFail('As senhas não conferem',btn);
if(p1&&!a)return obFail('Responda a pergunta secreta 🔑',btn);
curPhrase=genPhrase();
S={nome:nome,passHash:p1?hash(p1+salt()):null,q:q,qHash:hash(a.toLowerCase()+salt()),phraseHash:hash(curPhrase.toLowerCase().trim()),criadoEm:new Date().toISOString(),coins:0,hearts:0,unlocked:[1],saved:[],read:[],savedWords:[],lastBonus:'',lastSave:''};
jset(K.jardim,S);log('conta','Jardim criado por '+nome,'🌱');
if(p1){document.getElementById('phraseWords').textContent=curPhrase;document.getElementById('phraseModal').classList.add('on');}else{enter();}}
function copyPhrase(){navigator.clipboard.writeText(curPhrase).then(function(){toast('Frase copiada! Guarde bem 📋')}).catch(function(){toast('Copie manualmente: '+curPhrase)})}
function closePhrase(){document.getElementById('phraseModal').classList.remove('on');enter();}
function tryLogin(){if(!S)return;var p=document.getElementById('lgPass').value;
if(!S.passHash){enter();return}
if(hash(p+salt())===S.passHash){attempts=0;enter();}else{attempts++;toast(attempts>=5?'Use "Esqueci minha senha" 🔑':'Senha incorreta ('+attempts+'/5)');}}
function setRc(m){recMode=m;document.getElementById('rcT-ph').classList.toggle('on',m==='ph');document.getElementById('rcT-q').classList.toggle('on',m==='q');document.getElementById('rcPh').style.display=m==='ph'?'block':'none';document.getElementById('rcQ').style.display=m==='q'?'block':'none';}
function tryRecover(){if(!S)return;var ok=false;
if(recMode==='ph'){ok=hash(document.getElementById('rcPhrase').value.toLowerCase().trim())===S.phraseHash;}
else{ok=hash(document.getElementById('rcAns').value.trim().toLowerCase()+salt())===S.qHash;}
if(ok){recOk=true;showAuth('newpass');toast('Identidade confirmada! ✅');}else toast('Não confere. Tente de novo 🔑');}
function setNewPass(){if(!recOk)return;var p1=document.getElementById('npPass').value,p2=document.getElementById('npPass2').value;
if(p1.length<4){toast('Mínimo 4 caracteres');return}if(p1!==p2){toast('Não conferem');return}
S.passHash=hash(p1+salt());recOk=false;curPhrase=genPhrase();S.phraseHash=hash(curPhrase.toLowerCase().trim());jset(K.jardim,S);
document.getElementById('phraseWords').textContent=curPhrase;document.getElementById('phraseModal').classList.add('on');
log('conta','Senha redefinida','🔑');}
function lockApp(){entered=false;stopAllGames();document.getElementById('lgPass').value='';showAuth('login');toast('Jardim trancado 🔒');}
function wipeAll(){if(!confirm('Apagar TUDO deste aparelho (jardim, notas, registro)?'))return;Object.keys(K).forEach(function(k){try{localStorage.removeItem(k)}catch(e){}});location.reload();}
function save(){jset(K.jardim,S);hud();}
function hud(){if(!S)return;document.getElementById('coinView').textContent=S.coins;document.getElementById('heartView').textContent=S.hearts;}
function NM(){return S?S.nome:'você'}
function log(tipo,detalhe,valor){var a=jget(K.ativ,[]);a.unshift({ts:new Date().toISOString(),tipo:tipo,pessoa:NM(),detalhe:detalhe,valor:valor||''});if(a.length>500)a.length=500;jset(K.ativ,a);}
function addCoins(n){if(!n||n<=0)return;S.coins+=n;save();toast('+'+n+' moedas 🪙');log('moedas','Ganhou moedas','+'+n+' 🪙');}
function buzz(ms){try{navigator.vibrate&&navigator.vibrate(ms||10)}catch(e){}}
function cur(){var s=document.querySelector('.screen.on');return s?s.id.replace('s-',''):'auth'}
var hist=[];
function go(id){if(!entered){showAuth('login');return}stopAllGames();hist.push(cur());document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('on')});document.getElementById('s-'+id).classList.add('on');document.getElementById('backBtn').style.display='flex';document.querySelectorAll('#bottomNav button').forEach(function(b){b.classList.toggle('on',b.id==='nv-'+id)});if(id==='tempo')renderTempo();if(id==='diary')renderDiary();if(id==='registro')renderRegistro();window.scrollTo(0,0);}
function goBack(){stopAllGames();var p=hist.pop()||'message';document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('on')});document.getElementById('s-'+p).classList.add('on');document.querySelectorAll('#bottomNav button').forEach(function(b){b.classList.toggle('on',b.id==='nv-'+p)});}
function toast(m){var t=document.getElementById('toast');t.textContent=m;t.style.display='block';setTimeout(function(){t.style.display='none'},2600);}
function confetti(){var cs=getComputedStyle(document.documentElement);var cols=[cs.getPropertyValue('--accent').trim(),cs.getPropertyValue('--accent2').trim(),'#fbbf24','#ffffff'];for(var i=0;i<30;i++){(function(i){setTimeout(function(){var e=document.createElement('div');e.className='confetti';e.style.left=Math.random()*100+'vw';e.style.background=cols[i%4];document.body.appendChild(e);setTimeout(function(){e.remove()},3200)},i*40)})(i)}}
function enter(){entered=true;var v=jget(K.vis,[]);if(v.indexOf(today())<0){v.push(today());jset(K.vis,v)}log('visita','Entrou no jardim','🌻');refreshTheme();hud();document.getElementById('wallet').style.display='flex';document.getElementById('lockBtn').style.display='flex';document.getElementById('gardenName').textContent='Jardim de '+NM();document.getElementById('bottomNav').classList.add('show');go2('message');renderMessage();confetti();toast('Bem-vinda ao seu jardim, '+NM()+'! 🌻');}
function go2(id){document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('on')});document.getElementById('s-'+id).classList.add('on');document.querySelectorAll('#bottomNav button').forEach(function(b){b.classList.toggle('on',b.id==='nv-'+id)});window.scrollTo(0,0);}
var THEMES=[
{id:'primavera',nome:'Primavera em Flor',emoji:'🌸',bg1:'#f9a8d4',bg2:'#86efac',ac:'#ec4899',ac2:'#10b981',card:'#fdf2f8',frase:'🌸 Primavera: tempo de florescer!'},
{id:'verao',nome:'Verão Solar',emoji:'☀️',bg1:'#fb923c',bg2:'#f43f5e',ac:'#f97316',ac2:'#fbbf24',card:'#fff7ed',frase:'☀️ Verão: energia de sol pra você!'},
{id:'outono',nome:'Outono Aconchego',emoji:'🍁',bg1:'#d97706',bg2:'#7c2d12',ac:'#b45309',ac2:'#fbbf24',card:'#fef3c7',frase:'🍁 Outono: aconchego e calma.'},
{id:'inverno',nome:'Inverno Cobertor',emoji:'☕',bg1:'#475569',bg2:'#1e293b',ac:'#6366f1',ac2:'#a5b4fc',card:'#f1f5f9',frase:'☕ Inverno: descansar também é florescer.'},
{id:'flores',nome:'Flores Amarelas',emoji:'🌻',bg1:'#667eea',bg2:'#5b3d8f',ac:'#e8930c',ac2:'#f5c33b',card:'#f2f4fb',frase:'🌻 Memória viva: 21 de setembro!'},
{id:'natal',nome:'Natal de Luz',emoji:'🎄',bg1:'#166534',bg2:'#14532d',ac:'#dc2626',ac2:'#f87171',card:'#fef2f2',frase:'🎄 Natal: luz e gratidão.'},
{id:'anonovo',nome:'Ano Novo',emoji:'🎆',bg1:'#1e3a8a',bg2:'#0f172a',ac:'#fbbf24',ac2:'#fde68a',card:'#eff6ff',frase:'🎆 Ano Novo: novo ciclo floresce.'}];
var EVENTS=[{t:'flores',i:[9,21],f:[9,23]},{t:'natal',i:[12,15],f:[12,26]},{t:'anonovo',i:[12,30],f:[1,3]}];
function season(m){return (m>=3&&m<=5)?'outono':(m>=6&&m<=8)?'inverno':(m>=9&&m<=11)?'primavera':'verao'}
function inEv(e,m,d){var st=e.i[0]*100+e.i[1],en=e.f[0]*100+e.f[1],cu=m*100+d;return st<=en?(cu>=st&&cu<=en):(cu>=st||cu<=en)}
function themeFor(y,m,d){for(var i=0;i<EVENTS.length;i++){if(inEv(EVENTS[i],m,d))return EVENTS[i].t}return season(m)}
var curTheme=null,manualTheme=jget(K.pref,{}).manual||null;
function applyTheme(id){var t=THEMES.filter(function(x){return x.id===id})[0]||THEMES[0];var r=document.documentElement.style;r.setProperty('--bg1',t.bg1);r.setProperty('--bg2',t.bg2);r.setProperty('--accent',t.ac);r.setProperty('--accent2',t.ac2);r.setProperty('--card',t.card);document.getElementById('themeEmoji').textContent=t.emoji;document.getElementById('themeFrase').textContent=t.frase;curTheme=id;var l=jget(K.temas,[]);if(l.indexOf(id)<0){l.push(id);jset(K.temas,l)}}
function refreshTheme(){var d=new Date();applyTheme(manualTheme||themeFor(d.getFullYear(),d.getMonth()+1,d.getDate()))}
function setManual(id){manualTheme=id;var p=jget(K.pref,{});p.manual=id;jset(K.pref,p);refreshTheme();if(entered)renderTempo();toast(id?'Modo memória ativado 📸':'Tema automático 🌻');}
var MSGS=[["{n}, você é aquela pessoa rara que transforma a vida dos outros apenas com sua presença.","Continue sendo essa força da natureza! 💛✨"],["Sua amizade é como um girassol: sempre busca a luz e ilumina todos ao redor.","Você é presente pra quem te conhece! 🌻"],["{n}, sua força e determinação são verdadeiramente inspiradoras.","Continue acreditando no seu potencial! ✨"],["Cada risada sua é contagiante e transforma dias comuns.","Seu sorriso é medicina! 😊💛"],["Você tem um coração enorme e uma alma que brilha mais que o sol.","O mundo precisa de mais pessoas como você! 💫"],["{n}, sua energia positiva transforma qualquer ambiente.","Continue sendo inspiração! 🌟"],["Sua amizade é um tesouro raro guardado com carinho.","Pessoas como você fazem a vida valer a pena! 💛"],["Você é prova viva de que bondade e alegria mudam o mundo.","Continue espalhando amor! 🌻"],["{n}, sua resiliência é admirável: graça de guerreira.","Cada desafio te fortalece! 💪"],["Sua criatividade e inteligência são impressionantes.","Continue explorando seus talentos! 🚀"],["Você tem o dom de fazer todos se sentirem acolhidos.","Seu coração é presente! 💛"],["{n}, sua autenticidade é sua maior força.","Nunca apague seu brilho! ✨"],["Sua alegria transforma qualquer dia em celebração.","Continue espalhando felicidade! 🎉"],["Você é aquela amiga leal, carinhosa e incrível.","Sua amizade é tesouro! 💛"],["{n}, sua determinação é inspiradora. Imparável.","Persiga seus sonhos! 🌟"],["Sua presença traz paz: porto seguro.","Raio de sol em dia nublado! ☀️"],["{n}, você é mais forte e mais amada do que pensa.","Acredite em você! 💪"],["Sua bondade faz do mundo um lugar melhor.","Continue espalhando amor! 💛"],["Você tem luz que ilumina dias escuros.","Sua energia é mágica! ✨"],["{n}, você é rara e verdadeiramente especial.","O mundo é melhor com você! 🌻💛"]];
function dayOfYear(){var n=new Date();return Math.floor((n-new Date(n.getFullYear(),0,0))/864e5)}
function renderMessage(){document.getElementById('msgTitle').textContent='Sua Mensagem de Hoje, '+NM()+' ✨';var m=MSGS[Math.floor((dayOfYear()-1)/18.25)%20];document.getElementById('msgQuote').textContent='"'+m[0].split('{n}').join(NM())+'"';document.getElementById('msgReflect').textContent=m[1];document.getElementById('msgEd').textContent='Edição #'+dayOfYear();var pill=document.getElementById('bonusPill');if(S.lastBonus!==today()){S.hearts+=3;S.lastBonus=today();save();pill.textContent='💛 Bônus Diário: +3 Corações! ✨';log('bonus','Bônus diário coletado','+3 💛');}else pill.textContent='💛 Bônus de hoje já coletado.';}
function saveHeart(){if(S.lastSave===today()){toast('Você já salvou hoje! 💛');return}S.lastSave=today();S.hearts+=1;save();toast('Salvo no coração! +1 💛');log('coracao','Salvou a mensagem','+1 💛');confetti();}
var calView=new Date();
setInterval(function(){var n=new Date();var c=document.getElementById('clock');if(c)c.textContent=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0')+':'+String(n.getSeconds()).padStart(2,'0')},1000);
function calMove(d){calView.setMonth(calView.getMonth()+d);renderCal()}
function renderCal(){var y=calView.getFullYear(),m=calView.getMonth();document.getElementById('calTitle').textContent=calView.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});var notas=jget(K.notas,[]),vis=jget(K.vis,[]);var h='';['D','S','T','Q','Q','S','S'].forEach(function(d){h+='<div class="calDow">'+d+'</div>'});for(var i=0;i<new Date(y,m,1).getDay();i++)h+='<div class="calDay blank"></div>';for(var d=1;d<=new Date(y,m+1,0).getDate();d++){var ds=fmt(new Date(y,m,d));var ev=null;for(var e=0;e<EVENTS.length;e++){if(inEv(EVENTS[e],m+1,d)){ev=EVENTS[e];break}}var nn=notas.filter(function(n){return n.data===ds});var mk='';if(ev)mk+=THEMES.filter(function(t){return t.id===ev.t})[0].emoji;if(nn.some(function(n){return n.arcada}))mk+='◦';else if(nn.length)mk+='•';if(vis.indexOf(ds)>=0)mk+='✓';h+='<div class="calDay'+(ds===today()?' today':'')+'" onclick="showDay(\''+ds+'\')">'+d+'<span class="mk">'+mk+'</span></div>'}document.getElementById('calGrid').innerHTML=h;}
function showDay(ds){var notas=jget(K.notas,[]).filter(function(n){return n.data===ds});document.getElementById('dayPanel').innerHTML='<div class="quote-card"><b style="color:#8a3c1a">📅 '+new Date(ds+'T12:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'long'})+'</b>'+(notas.length?notas.map(function(n){return '<p class="sub" style="margin:6px 0">'+(n.humor||'📝')+' '+(n.titulo||n.texto.slice(0,40)+'...')+'</p>'}).join(''):'<p class="sub" style="margin:6px 0">Nenhuma anotação neste dia.</p>')+'<button class="btn mini gold" onclick="newNote(\''+ds+'\')">✍️ Anotar neste dia</button></div>';}
function renderTempo(){var n=new Date();document.getElementById('dateFull').textContent=n.toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long',year:'numeric'});var h=n.getHours();document.getElementById('greet').textContent=(h<12?'☀️ Bom dia':h<18?'🌤️ Boa tarde':'🌙 Boa noite')+', '+NM()+'! O Vesper acompanha você.';var act=null;for(var i=0;i<EVENTS.length;i++){if(inEv(EVENTS[i],n.getMonth()+1,n.getDate())){act=EVENTS[i];break}}var cd='';if(act){var t=THEMES.filter(function(x){return x.id===act.t})[0];cd='🎉 Modo ativo hoje: '+t.emoji+' '+t.nome+'!';}else{var ne=null;for(var y=n.getFullYear();y<=n.getFullYear()+1&&!ne;y++){for(var e=0;e<EVENTS.length;e++){var st=new Date(y,EVENTS[e].i[0]-1,EVENTS[e].i[1]);if(st>=new Date(n.getFullYear(),n.getMonth(),n.getDate())){ne={t:THEMES.filter(function(x){return x.id===EVENTS[e].t})[0],days:Math.ceil((st-n)/864e5)};break}}}}cd=ne?'⏳ Faltam '+ne.days+' dias para '+ne.t.emoji+' '+ne.t.nome:'';}document.getElementById('countdown').textContent=cd;renderCal();document.getElementById('memGallery').innerHTML=jget(K.temas,[]).map(function(id){var t=THEMES.filter(function(x){return x.id===id})[0];return t?'<button class="btn mini ghost" onclick="setManual(\''+id+'\')">'+t.emoji+' '+t.nome+'</button>':''}).join(' ');document.getElementById('autoThemeBtn').style.display=manualTheme?'flex':'none';}
var diaryTab='all',editingId=null,saveTimer=null,curMood='😊';
var MOODS=['😊','😌','😔','💪','🙏',''];
function setDiaryTab(t){diaryTab=t;['all','pin','arc'].forEach(function(x){document.getElementById('dt-'+x).classList.toggle('on',x===t)});renderDiary();}
function renderDiary(){var q=(document.getElementById('searchNote').value||'').toLowerCase();var notas=jget(K.notas,[]);if(diaryTab==='pin')notas=notas.filter(function(n){return n.fixada&&!n.arcada});else if(diaryTab==='arc')notas=notas.filter(function(n){return n.arcada});else notas=notas.filter(function(n){return !n.arcada});if(q)notas=notas.filter(function(n){return ((n.titulo||'')+n.texto).toLowerCase().indexOf(q)>=0});notas.sort(function(a,b){return (b.data||'').localeCompare(a.data||'')});document.getElementById('noteList').innerHTML=notas.length?notas.map(function(n){return '<div class="note-item'+(n.fixada?' pin':'')+(n.arcada?' arc':'')+'"><b>'+(n.humor||'📝')+' '+(n.titulo||'Sem título')+'</b><p>'+n.texto.slice(0,120)+(n.texto.length>120?'...':'')+'</p><div class="note-meta">📅 '+n.data+(n.fixada?' • 📌':'')+(n.arcada?' • 🗄️':'')+'</div><button class="btn mini ghost" onclick="editNote(\''+n.id+'\')">✏️ Abrir</button></div>'}).join(''):'<p class="sub">Nenhuma anotação por aqui ainda. 🌸</p>';}
function newNote(data){editingId=null;go('note');document.getElementById('nData').value=data||today();document.getElementById('nTitulo').value='';document.getElementById('nTexto').value='';curMood='😊';renderMoods();document.getElementById('saveState').textContent='';updNoteBtns(null);}
function editNote(id){var n=jget(K.notas,[]).filter(function(x){return x.id===id})[0];if(!n)return;editingId=id;go('note');document.getElementById('nData').value=n.data;document.getElementById('nTitulo').value=n.titulo||'';document.getElementById('nTexto').value=n.texto;curMood=n.humor||'😊';renderMoods();updNoteBtns(n);}
function renderMoods(){document.getElementById('moodPick').innerHTML=MOODS.map(function(m){return '<button class="chip'+(m===curMood?' on':'')+'" onclick="pickMood(\''+m+'\')">'+m+'</button>'}).join('');}
function pickMood(m){curMood=m;renderMoods();autoSave();}
function updNoteBtns(n){document.getElementById('pinBtn').textContent=n&&n.fixada?'📌 Desafixar':'📌 Fixar';document.getElementById('arcBtn').textContent=n&&n.arcada?'🗄️ Restaurar':'🗄️ Arcar';}
function autoSave(){clearTimeout(saveTimer);document.getElementById('saveState').textContent='✍️ escrevendo...';saveTimer=setTimeout(function(){if(persistNote())document.getElementById('saveState').textContent='💾 salvo automaticamente';},600);}
function persistNote(){var titulo=document.getElementById('nTitulo').value,texto=document.getElementById('nTexto').value;if(!editingId&&!titulo.trim()&&!texto.trim())return null;var notas=jget(K.notas,[]);var data={id:editingId||('n_'+Date.now()),data:document.getElementById('nData').value||today(),titulo:titulo,texto:texto,humor:curMood,fixada:false,arcada:false,criadaEm:new Date().toISOString(),editadaEm:new Date().toISOString()};var i=-1;for(var k=0;k<notas.length;k++){if(notas[k].id===data.id){i=k;break}}if(i>=0){data.fixada=notas[i].fixada;data.arcada=notas[i].arcada;data.criadaEm=notas[i].criadaEm;notas[i]=data;}else{notas.unshift(data);log('nota','Criou anotação','📝');}editingId=data.id;jset(K.notas,notas);updNoteBtns(data);return data;}
function togglePin(){if(!editingId&&!persistNote()){toast('Escreva algo primeiro ✍️');return}var notas=jget(K.notas,[]);var t=notas.filter(function(x){return x.id===editingId})[0];t.fixada=!t.fixada;jset(K.notas,notas);updNoteBtns(t);toast(t.fixada?'Fixada! 📌':'Desafixada.');log('nota',t.fixada?'Fixou anotação':'Desafixou','📌');}
function toggleArc(){if(!editingId&&!persistNote()){toast('Escreva algo primeiro ✍️');return}var notas=jget(K.notas,[]);var t=notas.filter(function(x){return x.id===editingId})[0];t.arcada=!t.arcada;jset(K.notas,notas);updNoteBtns(t);toast(t.arcada?'Arcada com carinho 🗄️':'Restaurada! 🌸');log('nota',t.arcada?'Arcou anotação':'Restaurou','🗄️');}
function delNote(){if(!editingId){go('diary');return}if(!confirm('Excluir esta anotação pra sempre?'))return;var notas=jget(K.notas,[]).filter(function(n){return n.id!==editingId});jset(K.notas,notas);log('nota','Excluiu anotação','🗑️');go('diary');}
var actFilter='all';
function setActFilter(f){actFilter=f;['all','vis','jog','not','poe'].forEach(function(x){document.getElementById('af-'+x).classList.toggle('on',x===f)});renderTimeline();}
function streak(){var vs=jget(K.vis,[]);var d=new Date();if(vs.indexOf(fmt(d))<0)d.setDate(d.getDate()-1);var s=0;while(vs.indexOf(fmt(d))>=0){s++;d.setDate(d.getDate()-1)}return s}
function renderRegistro(){var notas=jget(K.notas,[]),ativ=jget(K.ativ,[]);var jogos=ativ.filter(function(a){return a.tipo.indexOf('jogo')===0||a.tipo==='quiz'}).length;document.getElementById('statGrid').innerHTML='<div class="stat">🔥 Sequência<b>'+streak()+' dias</b></div><div class="stat">🪙 Moedas<b>'+S.coins+'</b></div><div class="stat">💛 Corações<b>'+S.hearts+'</b></div><div class="stat">🎮 Partidas<b>'+jogos+'</b></div><div class="stat">📝 Notas<b>'+notas.filter(function(n){return !n.arcada}).length+'</b></div><div class="stat">🌸 Poesias<b>'+S.unlocked.length+'/10</b></div>';renderTimeline();}
function renderTimeline(){var ativ=jget(K.ativ,[]);var f=ativ;if(actFilter==='vis')f=ativ.filter(function(a){return a.tipo==='visita'||a.tipo==='bonus'});if(actFilter==='jog')f=ativ.filter(function(a){return a.tipo.indexOf('jogo')===0||a.tipo==='quiz'||a.tipo==='moedas'});if(actFilter==='not')f=ativ.filter(function(a){return a.tipo==='nota'});if(actFilter==='poe')f=ativ.filter(function(a){return a.tipo==='poesia'});var g={};f.slice(0,80).forEach(function(a){var d=a.ts.slice(0,10);if(!g[d])g[d]=[];g[d].push(a)});document.getElementById('timeline').innerHTML=Object.keys(g).slice(0,15).map(function(d){return '<div class="tl-day"><b>📅 '+new Date(d+'T12:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'long'})+'</b>'+g[d].map(function(a){return '<div class="tl-item">'+a.ts.slice(11,16)+' • '+a.detalhe+' <b>'+a.valor+'</b></div>'}).join('')+'</div>'}).join('')||'<p class="sub">Seu histórico aparecerá aqui 🌱</p>';}
function exportBackup(){var data={};Object.keys(K).forEach(function(k){data[K[k]]=jget(K[k],null)});var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='vesper-'+NM()+'-backup.json';a.click();toast('Backup só seu! ⬇️');}
function importBackup(f){if(!f)return;var r=new FileReader();r.onload=function(){try{var d=JSON.parse(r.result);Object.keys(d).forEach(function(k){if(d[k]!==null)jset(k,d[k])});toast('Backup restaurado! 🌻');setTimeout(function(){location.reload()},1200)}catch(e){toast('Arquivo inválido 😔')}};r.readAsText(f);}
var MOTIV=[{t:'Um passo de cada vez também é progresso.',g:'💼 Trabalho'},{t:'O treino de hoje é o abraço no seu eu de amanhã.',g:'🏋️ Gym'},{t:'Cada repetição é uma promessa cumprida a você mesma.',g:'🏋️ Gym'},{t:'Você não precisa dar conta de tudo hoje. Só do hoje.',g:'💼 Trabalho'},{t:'Seu esforço de agora constrói algo que você vai agradecer.',g:'💼 Trabalho'},{t:'Força não é não cansar — é continuar mesmo cansada.',g:'🏋️ Gym'},{t:'Respira fundo. Uma tarefa de cada vez.',g:'💼 Trabalho'},{t:'Apareceu no treino? Já venceu. O resto é detalhe.',g:'🏋️ Gym'},{t:'Descansar também é florescer.',g:'🌙 Descanso'},{t:'Você já superou dias impossíveis. Esse também vai.',g:'💼 Trabalho'}];
var FRASES=['O dia não precisa começar perfeito — só começou.','Sua risada é remédio pra quem está por perto.','Você faz as pessoas se sentirem em casa — isso é raro.','Sua luz não se apaga nem nos dias mais escuros.','O mundo fica mais bonito porque você existe nele.','Pequenas alegrias também contam como felicidade.','Delicadeza e força cabem na mesma pessoa: você.','Hoje é um bom dia pra ser gentil com você mesma.','Flores não competem — só florescem. Seja flor.','Tem orgulho de você alguém que você nem imagina.'];
var VERS=[{t:'Este é o dia que o Senhor fez; regozijemo-nos e alegremo-nos nele.',r:'Salmos 118:24'},{t:'Tudo posso naquele que me fortalece.',r:'Filipenses 4:13'},{t:'Os que esperam no Senhor renovam as suas forças.',r:'Isaías 40:31'},{t:'Seja forte e corajosa!... o Senhor estará com você por onde andar.',r:'Josué 1:9'},{t:'Venham a mim, todos os cansados, e eu lhes darei descanso.',r:'Mateus 11:28'},{t:'O Senhor é a minha força e o meu escudo.',r:'Salmos 28:7'},{t:'Entregue suas preocupações ao Senhor, e ele a susterá.',r:'Salmos 55:22'},{t:'A alegria do coração é um bom remédio.',r:'Provérbios 17:22'},{t:'De manhã, Senhor, ouves a minha voz.',r:'Salmos 5:3'},{t:'Eu bem sei os pensamentos que tenho a vosso respeito... de paz.',r:'Jeremias 29:11'}];
var wordTab='mot',wordOff={mot:0,fra:0,ver:0};
function setWordTab(t){wordTab=t;['mot','fra','ver'].forEach(function(x){document.getElementById('tab-'+x).classList.toggle('on',x===t)});renderWord();}
function wordArr(){return wordTab==='mot'?MOTIV:wordTab==='fra'?FRASES:VERS}
function renderWord(){var arr=wordArr();var it=arr[(dayOfYear()+wordOff[wordTab])%arr.length];var c=document.getElementById('wordCard');if(wordTab==='mot')c.innerHTML='<span class="badge-tag green">'+it.g+'</span><p class="quote" style="margin-top:8px">'+it.t+'</p>';else if(wordTab==='fra')c.innerHTML='<span class="badge-tag">✨ Frase</span><p class="quote" style="margin-top:8px">'+it+'</p>';else c.innerHTML='<span class="badge-tag purple">🙏 Versículo</span><p class="quote" style="margin-top:8px">"'+it.t+'"</p><p style="text-align:right;color:#8a3c1a;font-weight:700;margin-top:6px">— '+it.r+'</p>';}
function nextWord(){wordOff[wordTab]++;renderWord();}
function saveWord(){var key=wordTab+':'+((dayOfYear()+wordOff[wordTab])%wordArr().length);if(S.savedWords.indexOf(key)>=0){toast('Já guardada! 💛');return}S.savedWords.push(key);S.hearts+=1;save();toast('Palavra guardada! +1 💛');}
var SENSO={suave:.6,normal:1,rapido:1.8};
var TP={ptr:null,x:0,y:0,ax:0,ay:0,sens:SENSO[jget(K.pref,{}).sens||'normal']};
var ring=document.getElementById('touchRing');
function showRing(x,y){ring.style.display='block';ring.style.left=x+'px';ring.style.top=y+'px'}
function hideRing(){ring.style.display='none'}
function tpBind(el){if(el._tp)return;el._tp=1;
el.addEventListener('pointerdown',function(e){if(TP.ptr!==null)return;TP.ptr=e.pointerId;TP.x=e.clientX;TP.y=e.clientY;showRing(e.clientX,e.clientY);e.preventDefault();});
el.addEventListener('pointermove',function(e){if(e.pointerId!==TP.ptr)return;TP.ax+=e.clientX-TP.x;TP.ay+=e.clientY-TP.y;TP.x=e.clientX;TP.y=e.clientY;showRing(e.clientX,e.clientY);e.preventDefault();});
var up=function(e){if(e.pointerId!==TP.ptr)return;TP.ptr=null;TP.ax=0;TP.ay=0;hideRing();};
el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);}
function tpConsume(){var d={dx:TP.ax,dy:TP.ay};TP.ax=0;TP.ay=0;if(Math.abs(d.dx)<2)d.dx=0;if(Math.abs(d.dy)<2)d.dy=0;return d}
function setSens(s){TP.sens=SENSO[s];var p=jget(K.pref,{});p.sens=s;jset(K.pref,p);['suave','normal','rapido'].forEach(function(x){document.getElementById('sn-'+x).classList.toggle('on',x===s)});toast('Sensibilidade: '+s+' 🎚️');}
function fixedLoop(g,step,render){g._last=performance.now();g._acc=0;var H=1/120;var frame=function(t){if(!g._run)return;g._raf=requestAnimationFrame(frame);var dt=(t-g._last)/1000;g._last=t;if(dt>.25)dt=.25;g._acc+=dt;while(g._acc>=H){if(!g.paused)step(H);g._acc-=H}render();};g._run=true;g._raf=requestAnimationFrame(frame);}
function stopLoop(g){if(g){g._run=false;cancelAnimationFrame(g._raf)}}
var resumeBtn=null;
function makeResume(){resumeBtn=document.createElement('button');resumeBtn.className='btn gold';resumeBtn.style.cssText='position:fixed;bottom:74px;left:50%;transform:translateX(-50%);width:auto;padding:12px 26px;z-index:700;display:none';resumeBtn.textContent='▶ Continuar jogo';resumeBtn.onclick=function(){[gameSt,aimSt,birdSt,snakeSt,mkSt].forEach(function(g){if(g)g.paused=false});if(gameSt)document.getElementById('pauseBtn').innerHTML='⏸ Pausar';resumeBtn.style.display='none';};document.body.appendChild(resumeBtn);}
function pauseAll(){var any=false;[gameSt,aimSt,birdSt,snakeSt,mkSt].forEach(function(g){if(g){g.paused=true;any=true}});if(any&&resumeBtn){resumeBtn.style.display='flex';toast('Jogo pausado 🌸')}}
document.addEventListener('visibilitychange',function(){if(document.hidden)pauseAll()});
var gameSt=null,aimSt=null,birdSt=null,snakeSt=null,mkSt=null;
function stopAllGames(){stopLoop(gameSt);stopLoop(birdSt);stopLoop(snakeSt);stopLoop(mkSt);if(aimSt){clearInterval(aimSt.tick);clearInterval(aimSt.spawn)}gameSt=aimSt=birdSt=snakeSt=mkSt=null;hideRing();TP.ptr=null;if(resumeBtn)resumeBtn.style.display='none';}
var CW=340,CH=320;
function popAt(host,x,y,txt){var p=document.createElement('div');p.className='pop';p.textContent=txt;p.style.left=((host.offsetLeft||0)+x)+'px';p.style.top=((host.offsetTop||0)+y)+'px';(host.parentNode||document.body).appendChild(p);setTimeout(function(){p.remove()},700);}
function startGame(){stopAllGames();go2('game');gameSt={score:0,timer:0,spawnT:0,paused:false,flowers:[],px:CW/2,tL:30};document.getElementById('gEnd').innerHTML='';var cv=document.getElementById('chuvaCv');tpBind(cv);cv.onpointerdown=function(e){var r=cv.getBoundingClientRect();var x=(e.clientX-r.left)*(CW/r.width),y=(e.clientY-r.top)*(CH/r.height);for(var i=0;i<gameSt.flowers.length;i++){var f=gameSt.flowers[i];if(Math.hypot(f.x-x,f.y-y)<40){f.dead=true;catchFlower(cv,f.x,f.y);break}}};fixedLoop(gameSt,stepChuva,renderChuva);updG();}
function catchFlower(cv,x,y){gameSt.score++;S.hearts++;save();buzz(12);if(cv)popAt(cv,x,y,'+1 💛');updG();}
function stepChuva(dt){var g=gameSt;g.timer+=dt;var left=Math.max(0,30-Math.floor(g.timer));if(left!==g.tL){g.tL=left;updG()}if(g.timer>=30){endChuva();return}
g.spawnT+=dt;if(g.spawnT>.7){g.spawnT=0;g.flowers.push({x:30+Math.random()*(CW-60),y:-30,vy:90+Math.random()*60,e:['🌻','','🌸','💛'][Math.floor(Math.random()*4)]})}
var d=tpConsume();g.px=Math.max(45,Math.min(CW-45,g.px+d.dx*TP.sens*2.2));
var PY=CH-42;g.flowers.forEach(function(f){var py=f.y;f.y+=f.vy*dt;if(py<PY&&f.y>=PY&&Math.abs(f.x-g.px)<55){f.dead=true;catchFlower(document.getElementById('chuvaCv'),f.x,PY)}});
g.flowers=g.flowers.filter(function(f){return !f.dead&&f.y<CH+40});}
function renderChuva(){var cv=document.getElementById('chuvaCv');if(!cv)return;var x=cv.getContext('2d');x.clearRect(0,0,CW,CH);if(!gameSt)return;x.font='30px Segoe UI';gameSt.flowers.forEach(function(f){x.fillText(f.e,f.x-15,f.y+10)});x.fillStyle='#e8930c';x.beginPath();x.ellipse(gameSt.px,CH-14,55,26,0,Math.PI,0);x.fill();x.fillStyle='#fff';x.font='bold 11px Segoe UI';x.textAlign='center';x.fillText('CESTA DE AFETO',gameSt.px,CH-22);x.textAlign='left';}
function updG(){if(!gameSt)return;document.getElementById('gScore').textContent=gameSt.score+'/15';document.getElementById('gTime').textContent='00:'+String(gameSt.tL).padStart(2,'0');document.getElementById('gBar').style.width=Math.min(100,gameSt.score/15*100)+'%';}
function togglePause(){if(!gameSt)return;gameSt.paused=!gameSt.paused;document.getElementById('pauseBtn').innerHTML=gameSt.paused?'▶ Continuar':'⏸ Pausar';if(resumeBtn)resumeBtn.style.display='none';}
function endChuva(){var sc=gameSt.score;stopAllGames();log('jogo_chuva',sc+' flores',sc>=15?'+10 🪙':'');var e=document.getElementById('gEnd');if(sc>=15){addCoins(10);e.innerHTML='<div class="quote-card"><h2>🎉 META ALCANÇADA!</h2><p class="sub">'+sc+' flores! +10 🪙</p><button class="btn gold" onclick="startGame()">De novo ↺</button></div>';confetti();}else e.innerHTML='<div class="quote-card"><h2>🌸 Quase lá!</h2><p class="sub">'+sc+'/15 flores. Respire e tente de novo!</p><button class="btn gold" onclick="startGame()">Reiniciar ↺</button></div>';}
function startMonkey(){stopAllGames();go2('monkey');mkSt={score:0,timer:0,spawnT:0,paused:false,ban:[],mx:CW/2,tL:25};document.getElementById('mkEnd').innerHTML='';var cv=document.getElementById('mkCv');tpBind(cv);fixedLoop(mkSt,stepMonkey,renderMonkey);}
function stepMonkey(dt){var g=mkSt;g.timer+=dt;var left=Math.max(0,25-Math.floor(g.timer));if(left!==g.tL){g.tL=left;document.getElementById('mkTime').textContent=left+'s'}if(g.timer>=25){endMonkey();return}
g.spawnT+=dt;if(g.spawnT>.75){g.spawnT=0;var bx=g.mx+(Math.random()*1.2-.6)*CW;bx=Math.max(25,Math.min(CW-25,bx));g.ban.push({x:bx,y:-30,vy:110+Math.random()*60})}
var d=tpConsume();g.mx=Math.max(28,Math.min(CW-28,g.mx+d.dx*TP.sens*2.4));
var MY=CH-52;g.ban.forEach(function(b){var py=b.y;b.y+=b.vy*dt;if(py<MY&&b.y>=MY&&Math.abs(b.x-g.mx)<46){b.dead=true;g.score++;S.hearts++;save();buzz(12);document.getElementById('mkScore').textContent=g.score;popAt(document.getElementById('mkCv'),b.x,MY,'+1 💛')}});
g.ban=g.ban.filter(function(b){return !b.dead&&b.y<CH+40});}
function renderMonkey(){var cv=document.getElementById('mkCv');if(!cv)return;var x=cv.getContext('2d');x.clearRect(0,0,CW,CH);if(!mkSt)return;x.font='28px Segoe UI';mkSt.ban.forEach(function(b){x.fillText('🍌',b.x-14,b.y+10)});x.font='34px Segoe UI';x.fillText('🐵',mkSt.mx-17,CH-16);}
function endMonkey(){var sc=mkSt.score;stopAllGames();log('jogo_monito',sc+' bananas','+'+sc+' 🪙');addCoins(sc);document.getElementById('mkEnd').innerHTML='<div class="quote-card"><h2>🐵 Colheita completa!</h2><p class="sub">'+sc+' bananas • +'+sc+' 🪙</p><button class="btn gold" onclick="startMonkey()">De novo ↺</button><button class="btn ghost" onclick="go(\'arcade\')">Arcade</button></div>';confetti();}
function startBird(){stopAllGames();go2('bird');birdSt={y:CH/2,vy:0,pipes:[],score:0,over:false,t:0,spawnT:1.2,paused:false};document.getElementById('birdEnd').innerHTML='';document.getElementById('birdScore').textContent=0;var cv=document.getElementById('birdCv');cv.onpointerdown=function(e){e.preventDefault();if(birdSt&&!birdSt.over){birdSt.vy=-380;buzz()}};fixedLoop(birdSt,stepBird,renderBird);}
function stepBird(dt){var b=birdSt;if(b.over)return;b.t+=dt;b.vy+=1300*dt;b.y+=b.vy*dt;if(b.y<12){b.y=12;b.vy=0}
b.spawnT+=dt;var sp=Math.min(150,110+b.t*3);if(b.spawnT>1.5){b.spawnT=0;b.pipes.push({x:CW+40,gap:40+Math.random()*(CH-230),w:46})}
b.pipes.forEach(function(p){p.x-=sp*dt;if(!p.passed&&p.x+p.w<60){p.passed=true;b.score++;S.coins+=2;save();buzz();document.getElementById('birdScore').textContent=b.score}
if(p.x<84&&p.x+p.w>60){var y0=b.y+5,y1=b.y+21;if(y0<p.gap||y1>p.gap+150)b.over=true}});
b.pipes=b.pipes.filter(function(p){return p.x>-60});
if(b.y>CH-18)b.over=true;
if(b.over){stopLoop(birdSt);log('jogo_bird',b.score+' obstáculos','+'+(b.score*2)+' 🪙');document.getElementById('birdEnd').innerHTML='<div class="quote-card"><h2>🐦 Fim de voo!</h2><p class="sub">'+b.score+' obstáculos • +'+(b.score*2)+' 🪙</p><button class="btn gold" onclick="startBird()">De novo ↺</button><button class="btn ghost" onclick="go(\'arcade\')">Arcade</button></div>';confetti();}}
function renderBird(){var cv=document.getElementById('birdCv');if(!cv)return;var x=cv.getContext('2d');x.clearRect(0,0,CW,CH);if(!birdSt)return;x.fillStyle='#0d9f8a';birdSt.pipes.forEach(function(p){x.fillRect(p.x,0,p.w,p.gap);x.fillRect(p.x,p.gap+150,p.w,CH)});x.font='26px Segoe UI';x.fillText('🐦',60,birdSt.y+22);}
function rf(){return[Math.floor(Math.random()*13),Math.floor(Math.random()*13)]}
function startSnake(){stopAllGames();go2('snake');snakeSt={s:[[6,6],[5,6],[4,6]],d:[1,0],q:[],sx:0,sy:0,f:rf(),score:0,mt:0,paused:false};document.getElementById('snakeEnd').innerHTML='';document.getElementById('snakeScore').textContent=0;tpBind(document.getElementById('snakeCv'));fixedLoop(snakeSt,stepSnake,renderSnake);}
function stepSnake(dt){var g=snakeSt;if(!g)return;var d=tpConsume();g.sx+=d.dx;g.sy+=d.dy;
if(Math.abs(g.sx)>18||Math.abs(g.sy)>18){var nd=Math.abs(g.sx)>Math.abs(g.sy)?[g.sx>0?1:-1,0]:[0,g.sy>0?1:-1];var last=g.q.length?g.q[g.q.length-1]:g.d;if((nd[0]!==-last[0]||nd[1]!==-last[1])&&g.q.length<2)g.q.push(nd);g.sx=0;g.sy=0}
g.mt+=dt;if(g.mt<.16)return;g.mt=0;var dir=g.q.shift()||g.d;g.d=dir;var h=[g.s[0][0]+dir[0],g.s[0][1]+dir[1]];
if(h[0]<0||h[0]>12||h[1]<0||h[1]>12||g.s.some(function(s){return s[0]===h[0]&&s[1]===h[1]})){stopLoop(g);snakeSt=null;log('jogo_cobrita',g.score+' flores','+'+g.score+' 🪙');document.getElementById('snakeEnd').innerHTML='<div class="quote-card"><h2>🐍 Fim da trilha!</h2><p class="sub">'+g.score+' flores • +'+g.score+' 🪙</p><button class="btn gold" onclick="startSnake()">De novo ↺</button><button class="btn ghost" onclick="go(\'arcade\')">Arcade</button></div>';if(g.score)confetti();return}
g.s.unshift(h);if(h[0]===g.f[0]&&h[1]===g.f[1]){g.score++;S.coins++;save();buzz(12);document.getElementById('snakeScore').textContent=g.score;g.f=rf()}else g.s.pop();}
function renderSnake(){var cv=document.getElementById('snakeCv');if(!cv)return;var x=cv.getContext('2d');x.clearRect(0,0,260,260);if(!snakeSt)return;x.font='18px Segoe UI';x.fillText('🌻',snakeSt.f[0]*20+1,snakeSt.f[1]*20+18);snakeSt.s.forEach(function(s,i){x.fillStyle=i?'#7bc47f':'#e8930c';x.fillRect(s[0]*20+2,s[1]*20+2,16,16)});}
function setDir(x,y){if(snakeSt){var last=snakeSt.q.length?snakeSt.q[snakeSt.q.length-1]:snakeSt.d;if((x!==-last[0]||y!==-last[1])&&snakeSt.q.length<2)snakeSt.q.push([x,y])}}
function startAim(){stopAllGames();go2('aim');aimSt={hits:0,t:20,paused:false};document.getElementById('aimEnd').innerHTML='';document.getElementById('aimScore').textContent=0;document.getElementById('aimTime').textContent='20s';var area=document.getElementById('aimArea');area.innerHTML='';area.onpointerdown=function(e){if(!aimSt||aimSt.paused)return;var r=area.getBoundingClientRect();var x=e.clientX-r.left,y=e.clientY-r.top;var best=null,bd=1e9;area.querySelectorAll('.tgt').forEach(function(t){var tr=t.getBoundingClientRect();var cx=tr.left-r.left+tr.width/2,cy=tr.top-r.top+tr.height/2;var dist=Math.hypot(cx-x,cy-y);if(dist<tr.width/2+18&&dist<bd){bd=dist;best=t}});if(best){aimSt.hits++;document.getElementById('aimScore').textContent=aimSt.hits;buzz(12);popAt(area,parseFloat(best.style.left),parseFloat(best.style.top),'+1');best.remove()}};
aimSt.tick=setInterval(function(){if(!aimSt||aimSt.paused)return;aimSt.t--;document.getElementById('aimTime').textContent=aimSt.t+'s';if(aimSt.t<=0)endAim()},1000);
aimSt.spawn=setInterval(function(){if(!aimSt||aimSt.paused)return;var a=document.getElementById('aimArea');var t=document.createElement('div');t.className='tgt';t.style.left=Math.random()*(a.offsetWidth-60)+'px';t.style.top=Math.random()*(a.offsetHeight-60)+'px';t.textContent=['🎯','🌼','💛'][Math.floor(Math.random()*3)];a.appendChild(t);setTimeout(function(){t.remove()},1500)},800);}
function endAim(){var c=Math.floor(aimSt.hits/2);stopAllGames();log('jogo_mira',aimSt.hits+' acertos','+'+c+' 🪙');addCoins(c);document.getElementById('aimEnd').innerHTML='<div class="quote-card"><h2>🎯 Fim de jogo!</h2><p class="sub">'+aimSt.hits+' acertos • +'+c+' 🪙</p><button class="btn gold" onclick="startAim()">De novo ↺</button><button class="btn ghost" onclick="go(\'arcade\')">Arcade</button></div>';if(c)confetti();}
var QUIZ=[{q:'Significado das flores amarelas em 21/09?',o:['Fim de ano','Luz, amizade e novos começos','Renovar plantas','Obrigação'],c:1},{q:'Flores amarelas simbolizam?',o:['Tristeza','Raiva','Alegria e amizade','Distância'],c:2},{q:'Novela que popularizou?',o:['Floricienta','Rebelde','Chiquititas','Carrusel'],c:0},{q:'21/09 no hemisfério sul?',o:['Inverno','Outono','Primavera','Verão'],c:2},{q:'Qualidade sua?',o:['Ser incrível do seu jeito','Ser comum','Ser invisível','Nenhuma'],c:0},{q:'Amizade verdadeira nos dias difíceis?',o:['Julga','Apoia e acolhe','Ignora','Fofoca'],c:1},{q:'Atravessar um dia cansativo?',o:['Desistir','Respirar e seguir com carinho','Reclamar','Fugir'],c:1},{q:'O que você merece?',o:['Nada','Só o básico','Tudo de bom','Só obrigações'],c:2}];
var quizSt=null;
function goQuiz(){quizSt={i:0,ok:0,sel:null};go('quiz');renderQuiz();}
function renderQuiz(){var q=QUIZ[quizSt.i];document.getElementById('quizProg').textContent='Pergunta '+(quizSt.i+1)+' de 5';document.getElementById('quizBar').style.width=(((quizSt.i+1)/5)*100)+'%';document.getElementById('quizCard').innerHTML='<p style="text-align:left;color:#8a3c1a;font-weight:800;margin-bottom:10px">🌻 '+q.q+'</p>'+q.o.map(function(o,i){return '<button class="opt" onclick="selOpt('+i+')"><span class="letter">'+'ABCD'[i]+'</span><span>'+o+'</span></button>'}).join('')+'<button class="btn purple" onclick="confirmQuiz()">Confirmar ✨</button><button class="btn ghost" onclick="nextQuiz()">Pular</button>';quizSt.sel=null;}
function selOpt(i){quizSt.sel=i;document.querySelectorAll('.opt').forEach(function(e,j){e.classList.toggle('sel',j===i)});}
function confirmQuiz(){if(quizSt.sel===null){toast('Escolha uma opção! 🌸');return}var q=QUIZ[quizSt.i];var ok=quizSt.sel===q.c;if(ok){quizSt.ok++;S.coins+=5;S.hearts+=2;save()}document.querySelectorAll('.opt').forEach(function(e,j){e.onclick=null;if(j===q.c)e.classList.add('correct');if(j===quizSt.sel&&!ok)e.classList.add('wrong')});setTimeout(function(){if(ok)log('quiz','Acertou a pergunta '+(quizSt.i+1),'+5 🪙');document.getElementById('quizCard').innerHTML='<h2>'+(ok?'🎉 Acertou, '+NM()+'!':'🌸 Quase!')+'</h2><button class="btn purple" onclick="nextQuiz()">'+(quizSt.i<4?'Próxima →':'Resultado 🌻')+'</button>';if(ok)confetti()},600);}
function nextQuiz(){if(quizSt.i<4){quizSt.i++;renderQuiz()}else{log('jogo_quiz','Quiz: '+quizSt.ok+'/5','+'+(quizSt.ok*5)+' 🪙');document.getElementById('quizCard').innerHTML='<h2>🎯 Fim!</h2><p class="sub">'+quizSt.ok+'/5 • +'+(quizSt.ok*5)+' 🪙</p><button class="btn gold" onclick="openPoems(\'locked\')">Poesias 💝</button>';confetti()}}
var POEMS=[{id:1,t:'Força Interior',c:0,v:'Mesmo nas tempestades mais frias,\nsua raiz é feita de sol e luz.\nO vento pode até vergar o caule,\nmas jamais apagará a grandeza\nque floresce em seu peito.\n\nVocê não precisa ser forte o tempo todo;\nhá beleza também nas pausas e no silêncio.'},{id:2,t:'Você é Suficiente',c:5,v:'Quando o espelho não reflete sua beleza,\nlembre-se: você é perfeita do seu jeito,\núnica, especial, radiante e brilhante.\n\nVocê é suficiente exatamente como é.'},{id:3,t:'Novo Amanhecer',c:10,v:'Todo fim é um novo começo,\ntoda noite precede um amanhecer.\nMesmo nos dias mais escuros,\no sol vai voltar a aparecer.'},{id:4,t:'Coragem de Ser',c:15,v:'Tenha coragem de ser quem você é,\nmesmo que o mundo tente te moldar.\nSua autenticidade é sua força.'},{id:5,t:'Jardim Interior',c:20,v:'Dentro de você existe um jardim,\nonde florescem sonhos e esperança.\nRegue-o com amor e paciência.'},{id:6,t:'Mulher Guerreira',c:25,v:'Mulher, você é feita de aço e de flor,\nde lágrimas e risos, de dor e amor.\nLevanta a cabeça, guerreira!'},
{id:7,t:'Tempo de Florescer',c:30,v:'Tudo tem seu tempo, minha querida,\nnem tudo acontece na hora que a gente quer.\nConfie no processo da vida.'},{id:8,t:'Você Não Está Só',c:35,v:'Quando a noite parecer longa demais,\nlembre-se: você nunca está só.\nExiste alguém torcendo pela sua mão.'},{id:9,t:'Renascer',c:40,v:'Assim como a fênix renasce das cinzas,\nvocê também pode se reinventar.'},{id:10,t:'Sua Luz Única',c:50,v:'Você tem uma luz que ninguém tem,\numa cor que só você pode pintar,\num jeito único de amar.'}];
function openPoems(f){f=f||'all';go('poems');['all','unlocked','locked'].forEach(function(x){document.getElementById('f-'+x).classList.toggle('on',x===f)});document.getElementById('poemCount').textContent=S.unlocked.length+'/10';document.getElementById('poemBar').style.width=(S.unlocked.length*10)+'%';var list=document.getElementById('poemList');list.innerHTML='';POEMS.forEach(function(p){var un=S.unlocked.indexOf(p.id)>=0;if(f==='unlocked'&&!un)return;if(f==='locked'&&un)return;var d=document.createElement('div');d.className='poem-item'+(un?'':' locked');d.innerHTML='<b>'+p.t+'</b><p>"'+p.v.split('\n')[0]+'..."</p>'+(un?'<button class="btn pink" onclick="openPoem('+p.id+')">Ler ♡</button>':(S.coins>=p.c?'<button class="btn gold" onclick="unlockPoem('+p.id+')">Desbloquear '+p.c+' 🪙</button>':'<button class="btn ghost" disabled>🔒 '+p.c+' 🪙</button>'));list.appendChild(d)});}
function unlockPoem(id){var p=POEMS.filter(function(x){return x.id===id})[0];if(S.coins<p.c){toast('Moedas insuficientes! Jogue 🪙');return}S.coins-=p.c;S.unlocked.push(id);save();log('poesia','Desbloqueou: '+p.t,'-'+p.c+' 🪙');confetti();openPoem(id);}
var curPoem=null;
function openPoem(id){curPoem=POEMS.filter(function(x){return x.id===id})[0];go('poem');document.getElementById('pvTitle').textContent=curPoem.t;document.getElementById('pvDed').textContent='Dedicado com carinho ao Cantinho de '+NM()+' 💛';document.getElementById('pvVerse').textContent='"'+curPoem.v+'"';document.getElementById('pvNum').textContent='🌸 Poesia '+curPoem.id+' de 10';if(S.read.indexOf(id)<0){S.read.push(id);S.hearts+=2;save();log('poesia','Leu: '+curPoem.t,'+2 💛');toast('+2 Corações 💛')}}
function savePoem(){if(S.saved.indexOf(curPoem.id)>=0){toast('Já guardada! 💛');return}S.saved.push(curPoem.id);S.hearts+=1;save();log('poesia','Guardou: '+curPoem.t,'+1 💛');toast('Guardada no coração! 💛')}
function hearPoem(){if('speechSynthesis'in window){speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(curPoem.v);u.lang='pt-BR';u.rate=.85;speechSynthesis.speak(u);toast('🎵 Ouvindo...')}else toast('Sem suporte a áudio 🎵')}
var AC=null,mute=jget(K.pref,{}).mute||false;
function blip(f,d){if(mute)return;try{AC=AC||new (window.AudioContext||window.webkitAudioContext)();if(AC.state==='suspended')AC.resume();var o=AC.createOscillator(),g=AC.createGain();o.type='sine';o.frequency.value=f||660;g.gain.value=.08;o.connect(g);g.connect(AC.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,AC.currentTime+(d||.09));o.stop(AC.currentTime+(d||.1))}catch(e){}}
var _buzz=buzz;buzz=function(ms){_buzz(ms);blip(ms>10?880:660)};
document.getElementById('muteBtn').onclick=function(){mute=!mute;var p=jget(K.pref,{});p.mute=mute;jset(K.pref,p);this.textContent=mute?'🔇 Som: desligado':'🔊 Som: ligado'};
if(mute)document.getElementById('muteBtn').textContent='🔇 Som: desligado';
var dTaps=0,dTapT=0;
function toggleDiag(){var d=document.getElementById('diagPanel');if(d){d.remove();return}d=document.createElement('div');d.id='diagPanel';d.style.cssText='position:fixed;top:64px;right:8px;background:rgba(0,0,0,.85);color:#4ade80;font:12px monospace;padding:10px;border-radius:14px;z-index:950;line-height:1.7;max-width:260px';d.innerHTML='🧪 VESPER DIAG<br>storage: '+(LS_OK?'OK':'MEMÓRIA')+'<br>jardim: '+(jget(K.jardim,null)?'existe':'vazio')+'<br>erros: '+window.__errs.length+'<br>tema: '+curTheme;document.body.appendChild(d)}
document.getElementById('authLogo').addEventListener('click',function(){var n=Date.now();if(n-dTapT>1500)dTaps=0;dTapT=n;dTaps++;if(dTaps>=5){dTaps=0;toggleDiag()}});
function guard(fn){return function(){try{return fn.apply(this,arguments)}catch(e){showErr(e.message);toast('Erro: '+e.message)}}}
createJardim=guard(createJardim);tryLogin=guard(tryLogin);tryRecover=guard(tryRecover);setNewPass=guard(setNewPass);enter=guard(enter);go=guard(go);goBack=guard(goBack);
function migrateOld(){var old=jget('vesper_perfil',null);if(old&&!jget(K.jardim,null)){old.nome='Celi';old.passHash=null;old.q=0;old.qHash='';old.phraseHash='';old.criadoEm=new Date().toISOString();jset(K.jardim,old);}}
function init(){makeResume();migrateOld();S=jget(K.jardim,null);refreshTheme();
if(!LS_OK){var w=document.createElement('p');w.className='sub';w.style.cssText='color:#b45309;font-weight:700;margin-top:8px';w.textContent='⚠️ Modo memória (preview): seus dados duram só enquanto esta aba estiver aberta.';document.getElementById('authOnboard').appendChild(w);}
if(S&&S.passHash){showAuth('login');}
else if(S){enter();}
else{showAuth('onboard');}
document.getElementById('lgPass').addEventListener('keypress',function(e){if(e.key==='Enter')tryLogin()});
document.getElementById('npPass2').addEventListener('keypress',function(e){if(e.key==='Enter')setNewPass()});}
try{init()}catch(e){showErr(e.message)}
